### ISSUE TITLE
Update Lumpy to hard code version

### ISSUE THREAD

**Issue by jharenza** [kids-first/kf-somatic-workflow#19]
Coded as pulling `latest`: https://github.com/kids-first/kf-somatic-workflow/blob/master/tools/lumpy-sv_somatic.cwl

**Comment by migbro** [comment]
This one was follieng git instructions and building "latest", however autobuild of latest might have had issues, so build using intended 0.2.13 might still have been used for a recently requested run.  Fixing build and looking into version run.

**Comment by migbro** [comment]
Inadvertent good news in that the "latest" build started failing before the latest release of lumpy because numpy, a dependency, has deprecated use on python2.  So the build would fail, leaning the current docker at the version we had intended top use the whole time.  Will close once I incorporate the new docker pull into the somatic wf tool.

**Comment by migbro** [comment]
Merged PR https://github.com/kids-first/kf-somatic-workflow/pull/37 has addressed this version issue.
